"""
Buddy Deployment Engine - Application Deployment Pipeline

Manages deployment pipelines for agent-generated applications, providing
Docker containerization, environment configuration, health checking, and
rolling updates across multiple deployment targets.
"""

from __future__ import annotations

import asyncio
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class DeploymentStatus(str, Enum):
    """Status of a deployment."""
    PENDING = "pending"
    BUILDING = "building"
    DEPLOYING = "deploying"
    RUNNING = "running"
    HEALTHY = "healthy"
    UNHEALTHY = "unhealthy"
    FAILED = "failed"
    STOPPED = "stopped"
    ROLLING_BACK = "rolling_back"


class DeploymentTarget(str, Enum):
    """Deployment target types."""
    DOCKER = "docker"
    KUBERNETES = "kubernetes"
    LOCAL = "local"
    CLOUD = "cloud"
    EDGE = "edge"


@dataclass
class DeploymentConfig:
    """Configuration for a deployment."""
    name: str
    target: DeploymentTarget = DeploymentTarget.LOCAL
    image: str = ""
    port: int = 8080
    env_vars: dict[str, str] = field(default_factory=dict)
    volumes: list[dict] = field(default_factory=list)
    resources: dict = field(default_factory=lambda: {
        "cpu": "0.5",
        "memory": "512Mi",
    })
    health_check_path: str = "/health"
    replicas: int = 1
    auto_restart: bool = True
    metadata: dict = field(default_factory=dict)


class Deployment:
    """A single deployment instance."""

    def __init__(self, deployment_id: str, config: DeploymentConfig):
        self.deployment_id = deployment_id
        self.config = config
        self.status = DeploymentStatus.PENDING
        self.container_id: str | None = None
        self.url: str = ""
        self.logs: list[str] = []
        self._created_at = time.time()
        self._started_at: float | None = None
        self._health_check_task: asyncio.Task | None = None

    def log(self, message: str):
        """Add a log entry."""
        entry = f"[{time.strftime('%H:%M:%S')}] {message}"
        self.logs.append(entry)

    async def build(self) -> bool:
        """Build the deployment artifact."""
        self.status = DeploymentStatus.BUILDING
        self.log(f"Building deployment: {self.config.name}")

        if self.config.target == DeploymentTarget.DOCKER:
            self.log("Building Docker image...")
            # Simulated Docker build
            await asyncio.sleep(0.5)
            self.config.image = f"buddy/{self.config.name}:latest"

        self.log("Build completed")
        return True

    async def deploy(self) -> bool:
        """Deploy the application."""
        self.status = DeploymentStatus.DEPLOYING
        self.log(f"Deploying to {self.config.target.value}...")

        # Simulated deployment
        self.container_id = f"container-{uuid.uuid4().hex[:12]}"
        await asyncio.sleep(0.3)

        self.status = DeploymentStatus.RUNNING
        self.url = f"http://localhost:{self.config.port}"
        self._started_at = time.time()
        self.log(f"Deployment running at {self.url}")

        return True

    async def health_check(self) -> DeploymentStatus:
        """Perform health check on the deployment."""
        if self.status not in (DeploymentStatus.RUNNING, DeploymentStatus.HEALTHY):
            return self.status

        # Simulated health check
        self.status = DeploymentStatus.HEALTHY
        return self.status

    async def stop(self) -> bool:
        """Stop the deployment."""
        self.log("Stopping deployment...")
        self.status = DeploymentStatus.STOPPED
        self.container_id = None
        self.url = ""
        return True

    async def rollback(self) -> bool:
        """Rollback to previous version."""
        self.status = DeploymentStatus.ROLLING_BACK
        self.log("Rolling back deployment...")
        await asyncio.sleep(0.3)
        await self.deploy()
        return True

    def to_dict(self) -> dict:
        return {
            "deployment_id": self.deployment_id,
            "name": self.config.name,
            "status": self.status.value,
            "target": self.config.target.value,
            "url": self.url,
            "port": self.config.port,
            "container_id": self.container_id,
            "created_at": self._created_at,
            "started_at": self._started_at,
            "recent_logs": self.logs[-10:],
        }


class DeploymentPipeline:
    """Manages the full deployment lifecycle for agent applications.

    Handles building, deploying, monitoring, and managing applications
    generated by agents. Supports Docker, Kubernetes, and local deployment
    targets with automated health checking and rollback capabilities.
    """

    def __init__(self):
        self._deployments: dict[str, Deployment] = {}
        self._total_deployments = 0
        self._total_builds = 0

    async def create_deployment(self, config: DeploymentConfig) -> Deployment:
        """Create and deploy a new application."""
        deployment_id = f"deploy-{uuid.uuid4().hex[:12]}"
        deployment = Deployment(deployment_id, config)
        self._deployments[deployment_id] = deployment
        self._total_deployments += 1

        # Build and deploy
        await deployment.build()
        self._total_builds += 1
        await deployment.deploy()

        return deployment

    def get_deployment(self, deployment_id: str) -> Deployment | None:
        """Get a deployment by ID."""
        return self._deployments.get(deployment_id)

    def list_deployments(self) -> list[Deployment]:
        """List all deployments."""
        return list(self._deployments.values())

    async def stop_deployment(self, deployment_id: str) -> bool:
        """Stop a deployment."""
        deployment = self.get_deployment(deployment_id)
        if deployment:
            return await deployment.stop()
        return False

    async def remove_deployment(self, deployment_id: str) -> bool:
        """Remove a deployment."""
        deployment = self._deployments.pop(deployment_id, None)
        if deployment:
            await deployment.stop()
            return True
        return False

    def get_stats(self) -> dict:
        return {
            "total_deployments": self._total_deployments,
            "total_builds": self._total_builds,
            "active_deployments": len(self._deployments),
            "deployments": [d.to_dict() for d in self._deployments.values()],
        }


# Global deployment pipeline instance
_deployment_pipeline: DeploymentPipeline | None = None


def get_deployment_pipeline() -> DeploymentPipeline:
    """Get or create the global deployment pipeline."""
    global _deployment_pipeline
    if _deployment_pipeline is None:
        _deployment_pipeline = DeploymentPipeline()
    return _deployment_pipeline