"""Buddy Agent Learning Loop — autonomous skill creation from interaction patterns

Watches agent execution traces and autonomously discovers reusable patterns,
generating new skills, updating memory heuristics, and refining agent behavior
over time through continuous observation and consolidation.
"""
from __future__ import annotations
import json
import logging
import hashlib
from datetime import datetime, timezone
from dataclasses import dataclass, field
from typing import Any

from openai import AsyncOpenAI

from config.settings import settings
from agent.memory import HierarchicalMemory

logger = logging.getLogger("buddy.learning")


@dataclass
class InteractionPattern:
    """A reusable pattern extracted from agent interactions."""
    id: str
    name: str
    trigger_keywords: list[str]
    response_template: str
    confidence: float
    usage_count: int = 0
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    source_agent: str = ""


@dataclass
class LearnedSkill:
    """A skill autonomously generated by the learning loop."""
    id: str
    name: str
    category: str
    description: str
    prompt_template: str
    params: list[dict]
    source_interactions: list[str]
    confidence: float
    usage_count: int = 0
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class LearningEngine:
    """Autonomous learning engine that observes interactions and creates new capabilities."""

    def __init__(self, agent_id: str, memory: HierarchicalMemory | None = None):
        self.agent_id = agent_id
        self.memory = memory
        self._patterns: dict[str, InteractionPattern] = {}
        self._learned_skills: dict[str, LearnedSkill] = {}
        self._observation_buffer: list[dict] = []
        self._buffer_threshold = 10
        self._client: AsyncOpenAI | None = None

        if settings.OPENAI_API_KEY:
            self._client = AsyncOpenAI(
                api_key=settings.OPENAI_API_KEY,
                base_url=settings.OPENAI_BASE_URL,
            )

    def observe(self, user_input: str, assistant_response: str, tool_calls: list | None = None) -> None:
        """Record an interaction for pattern analysis."""
        entry = {
            "user_input": user_input[:500],
            "assistant_response": assistant_response[:1000],
            "tool_calls": tool_calls or [],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self._observation_buffer.append(entry)

        if len(self._observation_buffer) >= self._buffer_threshold:
            # Trigger async analysis (fire-and-forget via background task)
            logger.debug(f"Observation buffer full ({len(self._observation_buffer)}), triggering analysis")

    async def analyze_and_extract(self) -> list[InteractionPattern]:
        """Analyze the observation buffer and extract reusable patterns."""
        if len(self._observation_buffer) < 3:
            return []

        patterns = []

        # Heuristic pattern extraction
        patterns.extend(self._extract_heuristic_patterns())

        # LLM-guided pattern extraction
        if self._client and len(self._observation_buffer) >= 5:
            llm_patterns = await self._extract_llm_patterns()
            patterns.extend(llm_patterns)

        # Clear buffer after extraction
        self._observation_buffer = []

        return patterns

    def _extract_heuristic_patterns(self) -> list[InteractionPattern]:
        """Extract patterns through heuristic analysis of recent interactions."""
        patterns = []
        # Group interactions by common keywords
        keyword_groups: dict[str, list[dict]] = {}
        for obs in self._observation_buffer[-10:]:
            key = obs["user_input"].lower().split()[:5]
            key_hash = hashlib.md5(" ".join(key).encode()).hexdigest()[:8]
            if key_hash not in keyword_groups:
                keyword_groups[key_hash] = []
            keyword_groups[key_hash].append(obs)

        for key_hash, group in keyword_groups.items():
            if len(group) >= 3:
                # Extract common keywords
                all_words = " ".join([g["user_input"].lower() for g in group])
                common_words = sorted(set(all_words.split()), key=all_words.split().count, reverse=True)[:5]

                pattern = InteractionPattern(
                    id=f"pat-{key_hash}",
                    name=f"Pattern: {common_words[0] if common_words else 'general'}",
                    trigger_keywords=common_words,
                    response_template=group[-1]["assistant_response"][:300],
                    confidence=min(0.3 + len(group) * 0.1, 0.9),
                    source_agent=self.agent_id,
                )
                self._patterns[pattern.id] = pattern
                patterns.append(pattern)

        return patterns

    async def _extract_llm_patterns(self) -> list[InteractionPattern]:
        """Use LLM to identify high-value interaction patterns."""
        if not self._client:
            return []

        samples = self._observation_buffer[-10:]
        sample_text = "\n".join(
            f"Q: {s['user_input'][:200]}\nA: {s['assistant_response'][:200]}"
            for s in samples
        )

        try:
            response = await self._client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{
                    "role": "system",
                    "content": (
                        "Analyze these agent interactions and identify recurring patterns that "
                        "could be turned into reusable skills. Return a JSON array of objects with: "
                        'name, trigger_keywords (array), response_template (string). '
                        "Only return patterns that appear at least 2 times."
                    ),
                }, {
                    "role": "user",
                    "content": sample_text,
                }],
                temperature=0.3,
                max_tokens=500,
            )

            content = response.choices[0].message.content or ""
            if not content:
                return []

            try:
                data = json.loads(content)
            except json.JSONDecodeError:
                # Try to extract JSON from markdown
                import re
                json_match = re.search(r'\[[\s\S]*\]', content)
                if json_match:
                    data = json.loads(json_match.group())
                else:
                    return []

            patterns = []
            for item in data if isinstance(data, list) else [data]:
                pid = f"pat-llm-{hashlib.md5(str(item).encode()).hexdigest()[:8]}"
                pattern = InteractionPattern(
                    id=pid,
                    name=item.get("name", "Learned Pattern"),
                    trigger_keywords=item.get("trigger_keywords", []),
                    response_template=item.get("response_template", ""),
                    confidence=0.7,
                    source_agent=self.agent_id,
                )
                self._patterns[pattern.id] = pattern
                patterns.append(pattern)

            return patterns

        except Exception as e:
            logger.debug(f"LLM pattern extraction failed: {e}")
            return []

    async def spawn_skill_from_pattern(
        self,
        pattern: InteractionPattern,
        category: str = "learned",
    ) -> LearnedSkill | None:
        """Convert a high-confidence interaction pattern into a reusable skill."""
        if pattern.confidence < 0.6:
            return None

        if not self._client:
            # Generate skill without LLM
            return LearnedSkill(
                id=f"skill-{pattern.id}",
                name=pattern.name,
                category=category,
                description=f"Auto-generated from {pattern.usage_count} interactions",
                prompt_template=pattern.response_template,
                params=[{"name": "input", "type": "string", "description": "Task input"}],
                source_interactions=[p["user_input"][:100] for p in self._observation_buffer[-3:]],
                confidence=pattern.confidence,
            )

        try:
            response = await self._client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{
                    "role": "system",
                    "content": (
                        "Generate a structured skill definition from this interaction pattern. "
                        'Return JSON: {"name": "...", "description": "...", "prompt_template": "...", '
                        '"params": [{"name": "...", "type": "string", "description": "..."}]}'
                    ),
                }, {
                    "role": "user",
                    "content": f"Pattern: {pattern.name}\nTemplate: {pattern.response_template}",
                }],
                temperature=0.3,
                max_tokens=400,
            )

            content = response.choices[0].message.content or ""
            data = json.loads(content) if content else {}

            skill = LearnedSkill(
                id=f"skill-{pattern.id}",
                name=data.get("name", pattern.name),
                category=category,
                description=data.get("description", f"Auto-generated skill"),
                prompt_template=data.get("prompt_template", pattern.response_template),
                params=data.get("params", [{"name": "input", "type": "string"}]),
                source_interactions=[p["user_input"][:100] for p in self._observation_buffer[-5:]],
                confidence=pattern.confidence,
            )
            self._learned_skills[skill.id] = skill
            logger.info(f"Learning engine spawned skill: {skill.name} (confidence: {skill.confidence})")
            return skill

        except Exception as e:
            logger.debug(f"Skill spawning failed: {e}")
            return None

    def get_patterns(self) -> list[dict]:
        """Get all learned patterns."""
        return [
            {
                "id": p.id, "name": p.name, "trigger_keywords": p.trigger_keywords,
                "confidence": p.confidence, "usage_count": p.usage_count,
                "created_at": p.created_at,
            }
            for p in self._patterns.values()
        ]

    def get_learned_skills(self) -> list[dict]:
        """Get all autonomously learned skills."""
        return [
            {
                "id": s.id, "name": s.name, "category": s.category,
                "description": s.description, "confidence": s.confidence,
                "usage_count": s.usage_count, "created_at": s.created_at,
            }
            for s in self._learned_skills.values()
        ]

    def record_pattern_usage(self, pattern_id: str) -> None:
        """Increment usage counter for a pattern."""
        if pattern_id in self._patterns:
            self._patterns[pattern_id].usage_count += 1

    def record_skill_usage(self, skill_id: str) -> None:
        """Increment usage counter for a learned skill."""
        if skill_id in self._learned_skills:
            self._learned_skills[skill_id].usage_count += 1

    def get_insights(self) -> list[dict]:
        """Get learning insights for the agent."""
        return [
            {
                "type": "patterns_discovered",
                "count": len(self._patterns),
                "description": f"Discovered {len(self._patterns)} reusable interaction patterns",
            },
            {
                "type": "skills_spawned",
                "count": len(self._learned_skills),
                "description": f"Spawned {len(self._learned_skills)} new skills from patterns",
            },
            {
                "type": "observations_pending",
                "count": len(self._observation_buffer),
                "description": f"{len(self._observation_buffer)} observations pending analysis",
            },
        ]


# Global learning engine
learning_engine = LearningEngine("system")